package op_onboard

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/DarkCaster/Perpetual/logging"
	"github.com/DarkCaster/Perpetual/op_init"
	"github.com/DarkCaster/Perpetual/utils"
)

func RolloutEnvironmentConfig(version, provider, keyMethod, key string, logger logging.ILogger) error {
	provider = strings.ToLower(strings.TrimSpace(provider))
	if !isSupportedRolloutProvider(provider) {
		return fmt.Errorf("unsupported provider %q, valid values: anthropic|openai|ollama|generic", provider)
	}

	keyMethod, err := normalizeAuthMethod(keyMethod)
	if err != nil {
		return err
	}

	configDir, err := utils.FindConfigDir()
	if err != nil {
		return err
	}

	if err = os.MkdirAll(configDir, 0755); err != nil {
		return err
	}

	if err = removeCurrentConfigFiles(configDir, logger); err != nil {
		return err
	}

	// Example files catalog, prefixed with version comment
	exampleCatalog := op_init.GetEnvExampleCatalogWithVersion(version)
	for _, example := range exampleCatalog {
		// Skip examples that have a corresponding real env file being generated:
		// the base (empty Provider) and the selected provider.
		if example.Provider == "" || example.Provider == provider {
			continue
		}
		if _, err = utils.SaveTextFile(filepathJoin(configDir, example.Filename), example.Content); err != nil {
			return err
		}
	}

	// Real env files catalog, prefixed with generated comment
	realCatalog := op_init.GetEnvCatalogWithTopString("# This file was generated by `perpetual onboard`.")

	baseExample, ok := findEnvExample(realCatalog, "")
	if !ok {
		return fmt.Errorf("base env example not found")
	}
	if _, err = utils.SaveTextFile(filepathJoin(configDir, strings.TrimSuffix(baseExample.Filename, ".example")), makeBaseEnvContent(baseExample.Content, provider)); err != nil {
		return err
	}

	providerExample, ok := findEnvExample(realCatalog, provider)
	if !ok {
		return fmt.Errorf("env example for provider %q not found", provider)
	}

	authValue := detectAuthValue(provider, key)
	if authValue == "" {
		logger.Warnf("Auth key for provider %s is not set; edit global env config or rerun onboard with -k\n", provider)
	}

	providerContent := makeProviderEnvContent(providerExample.Content, provider, keyMethod, authValue)
	if _, err = utils.SaveTextFile(filepathJoin(configDir, strings.TrimSuffix(providerExample.Filename, ".example")), providerContent); err != nil {
		return err
	}

	logger.Infof("Global env configuration created in %s", configDir)
	return nil
}

func isSupportedRolloutProvider(provider string) bool {
	switch provider {
	case "anthropic", "openai", "ollama", "generic":
		return true
	default:
		return false
	}
}

func normalizeAuthMethod(method string) (string, error) {
	method = strings.TrimSpace(method)
	if method == "" {
		return "", nil
	}

	switch strings.ToUpper(method) {
	case "BEARER":
		return "Bearer", nil
	case "BASIC":
		return "Basic", nil
	default:
		return "", fmt.Errorf("invalid auth method %q, valid values: Bearer|Basic", method)
	}
}

func removeCurrentConfigFiles(configDir string, logger logging.ILogger) error {
	entries, err := os.ReadDir(configDir)
	if err != nil {
		return err
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		path := filepathJoin(configDir, entry.Name())
		logger.Debugln("Removing old global config file:", path)
		if err = os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
	}

	return nil
}

func findEnvExample(catalog []op_init.EnvExampleFile, provider string) (op_init.EnvExampleFile, bool) {
	for _, example := range catalog {
		if example.Provider == provider {
			return example, true
		}
	}
	return op_init.EnvExampleFile{}, false
}

func makeBaseEnvContent(exampleContent, provider string) string {
	return upsertEnvQuoted(exampleContent, "LLM_PROVIDER", provider)
}

func makeProviderEnvContent(exampleContent, provider, keyMethod, authValue string) string {
	content := exampleContent
	prefix := strings.ToUpper(provider)

	switch provider {
	case "anthropic", "openai":
		content = upsertEnvQuoted(content, prefix+"_API_KEY", authValue)

	case "ollama", "generic":
		if keyMethod != "" {
			content = upsertEnvQuoted(content, prefix+"_AUTH_TYPE", keyMethod)
		}
		if authValue != "" {
			content = upsertEnvQuoted(content, prefix+"_AUTH", authValue)
		}
	}

	return content
}

func detectAuthValue(provider, explicitKey string) string {
	if strings.TrimSpace(explicitKey) != "" {
		return explicitKey
	}

	prefix := strings.ToUpper(provider)
	for _, name := range []string{prefix + "_AUTH", prefix + "_API_KEY"} {
		if value, ok := os.LookupEnv(name); ok && strings.TrimSpace(value) != "" {
			return value
		}
	}

	return ""
}

func upsertEnvQuoted(content, name, value string) string {
	line := name + "=" + strconv.Quote(value)
	rx := regexp.MustCompile(`(?m)^\s*#?\s*` + regexp.QuoteMeta(name) + `=.*$`)

	if rx.MatchString(content) {
		return rx.ReplaceAllString(content, line)
	}

	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + line + "\n"
}

func filepathJoin(elem ...string) string {
	return strings.Join(elem, string(os.PathSeparator))
}
